-- V1: 对话会话主表
CREATE TABLE conversations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id       VARCHAR(64)  NOT NULL UNIQUE,
    title           VARCHAR(255) DEFAULT '',
    model_name      VARCHAR(64)  NOT NULL,
    message_count   INT          DEFAULT 0,
    status          SMALLINT     DEFAULT 1,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX idx_conversations_memory_id ON conversations (memory_id);
CREATE INDEX idx_conversations_updated_at ON conversations (updated_at);

COMMENT ON TABLE conversations IS 'AI 对话会话主表';
COMMENT ON COLUMN conversations.memory_id IS '会话唯一标识（前端生成的 UUID）';
COMMENT ON COLUMN conversations.title IS '会话标题（首条用户消息截取）';
COMMENT ON COLUMN conversations.model_name IS '使用的模型名称';
COMMENT ON COLUMN conversations.status IS '状态：1=活跃 0=归档 -1=已删除';