-- V2: 对话消息明细表（行式存储，便于分析）
CREATE TABLE conversation_messages (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT       NOT NULL,
    role             VARCHAR(16)  NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content          TEXT         NOT NULL,
    thinking_content TEXT,
    attachments      JSONB        DEFAULT '{}',
    sequence_num     INT          NOT NULL,
    token_count      INT          DEFAULT 0,
    created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_msg_conv FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
);

CREATE INDEX idx_msg_conversation_seq ON conversation_messages (conversation_id, sequence_num);

COMMENT ON TABLE conversation_messages IS '对话消息明细表（行式存储，便于分析）';
COMMENT ON COLUMN conversation_messages.attachments IS '附件列表：[{type,url,filename}]';