-- V3: 对话上下文快照表（Kryo 序列化存储）
CREATE TABLE conversation_snapshots (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT       NOT NULL UNIQUE,
    snapshot_data    BYTEA        NOT NULL,
    version          BIGINT       NOT NULL DEFAULT 1,
    checksum         VARCHAR(64)  NOT NULL,
    kv_size          INT          DEFAULT 0,
    created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_snap_conv FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
);

CREATE INDEX idx_snap_conv_version ON conversation_snapshots (conversation_id, version);

COMMENT ON TABLE conversation_snapshots IS '对话上下文快照表（Kryo 序列化存储，Redis 的持久化后备）';
COMMENT ON COLUMN conversation_snapshots.snapshot_data IS 'Kryo 序列化的 ConversationContext 字节数组';
COMMENT ON COLUMN conversation_snapshots.checksum IS 'SHA-256 校验和（用于数据完整性验证）';
COMMENT ON COLUMN conversation_snapshots.kv_size IS '序列化后字节数';