-- V5: 知识库文档元数据 + 文档分块向量存储

CREATE TABLE knowledge_documents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename        VARCHAR(255) NOT NULL,
    file_type       VARCHAR(32)  NOT NULL,
    file_url        VARCHAR(1024),
    file_size       BIGINT       DEFAULT 0,
    chunk_count     INT          DEFAULT 0,
    status          VARCHAR(32)  DEFAULT 'PROCESSING',
    error_message   TEXT,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE knowledge_documents IS '知识库文档元数据表';

CREATE TABLE document_chunks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id     BIGINT       NOT NULL,
    chunk_index     INT          NOT NULL,
    content         TEXT         NOT NULL,
    embedding       vector(1536),
    metadata        JSONB        DEFAULT '{}',
    token_count     INT          DEFAULT 0,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_chunk_doc FOREIGN KEY (document_id) REFERENCES knowledge_documents(id) ON DELETE CASCADE
);

CREATE INDEX idx_chunks_doc_idx ON document_chunks (document_id, chunk_index);
CREATE INDEX idx_chunks_embedding ON document_chunks USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

COMMENT ON TABLE document_chunks IS '知识库文档分块表（含向量字段）';
COMMENT ON COLUMN document_chunks.embedding IS 'DashScope text-embedding-v3 输出 1536 维向量';
COMMENT ON COLUMN document_chunks.metadata IS '元数据（来源页码、章节标题等）';